name: Build latest and push to `public` branch

on:
  push:
    branches: [ "src" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out src branch
        uses: actions/checkout@v3
        with:
          ref: "src"

      - name: Install Python and Poetry
        uses: mmabey/action-setup-python@v0.3.1
        with:
          python-version: "3.10"

      - name: Build pages
        env:
          SPHINXOPTS: "-W"  # Turns all warnings into errors
        run: |
            cd src
            poetry run ablog build

      - uses: actions/upload-artifact@v3
        with:
          name: site_files
          path: build


  push-to-public:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out master branch
        uses: actions/checkout@v3
        with:
          ref: "public"

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Remove old files
        run: |
          git rm -rf docs/*

      - uses: actions/download-artifact@v3
        with:
          name: site_files
          path: docs/

      - name: Commit new files
        run: |
          git add .
          git restore --staged --worktree docs/CNAME
          git status
          git commit -m "Auto deploy `date -Idate`"
          git push
